import * as fs from 'node:fs/promises'
import { getExportsSize } from 'export-size'
import { filesize } from 'filesize'
import { markdownTable } from 'markdown-table'
import { version } from '../package.json'

async function run () {
  let md = '# Export size\n\n'
  md += 'generated by [export-size](https://github.com/antfu/export-size)<br>\n'
  md += `version: ${version}<br>\n`
  md += `date: ${new Date().toISOString()}\n\n`

  md += '> Please note this is bundle size for each individual export (excluding Vue and @floating-ui/dom). '
  md += 'Since we have a lot of shared utilities underneath each export, importing two '
  md += 'different exports does NOT necessarily mean the bundle size will be the sum of them (usually smaller). '
  md += 'Depending on the bundler and minifier you use, the final result might vary, this list is for reference only.'
  md += '\n\n'

  const { exports, packageJSON } = await getExportsSize({
    pkg: './packages/floating-vue',
    output: false,
    bundler: 'rollup',
    external: ['vue', '@floating-ui/dom'],
  })

  md += `<kbd>${packageJSON.name}</kbd>\n\n`

  md += markdownTable([
    ['Export', 'min+gzipped'],
    ...exports.map(i => [`\`${i.name}\``, filesize(i.minzipped)]),
  ])

  md += '\n'
  md = md.replace(/\r\n/g, '\n')

  await fs.writeFile('docs/api/export-size.md', md, 'utf-8')
}

run()
