/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowPadding: typeof import('./.vitepress/components/ArrowPadding.vue')['default']
    DropdownCloseDirectiveDemo: typeof import('./.vitepress/components/DropdownCloseDirectiveDemo.vue')['default']
    DropdownMobileDemo: typeof import('./.vitepress/components/DropdownMobileDemo.vue')['default']
    DropdownPlacement: typeof import('./.vitepress/components/DropdownPlacement.vue')['default']
    DropdownSimpleExample: typeof import('./.vitepress/components/DropdownSimpleExample.vue')['default']
    MenuSimpleExample: typeof import('./.vitepress/components/MenuSimpleExample.vue')['default']
    OffsetExample: typeof import('./.vitepress/components/OffsetExample.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorButton: typeof import('./.vitepress/components/SponsorButton.vue')['default']
    SubMenuExample: typeof import('./.vitepress/components/SubMenuExample.vue')['default']
    ThemeEditorVue: typeof import('./.vitepress/components/ThemeEditorVue.vue')['default']
    TooltipAsync: typeof import('./.vitepress/components/TooltipAsync.vue')['default']
    TooltipComponentExample: typeof import('./.vitepress/components/TooltipComponentExample.vue')['default']
    TooltipHtml: typeof import('./.vitepress/components/TooltipHtml.vue')['default']
    TooltipPlacement: typeof import('./.vitepress/components/TooltipPlacement.vue')['default']
    TooltipSimpleExample: typeof import('./.vitepress/components/TooltipSimpleExample.vue')['default']
    ZoomShowOnlyExample: typeof import('./.vitepress/components/ZoomShowOnlyExample.vue')['default']
  }
}
