/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowPadding: typeof import('./.vitepress/components/ArrowPadding.vue')['default']
    Button: typeof import('./.vitepress/components/theme-editor/Button.vue')['default']
    ConfigEditor: typeof import('./.vitepress/components/theme-editor/ConfigEditor.vue')['default']
    CreateTheme: typeof import('./.vitepress/components/theme-editor/CreateTheme.vue')['default']
    DropdownMobileDemo: typeof import('./.vitepress/components/DropdownMobileDemo.vue')['default']
    DropdownPlacement: typeof import('./.vitepress/components/DropdownPlacement.vue')['default']
    DropdownSimpleExample: typeof import('./.vitepress/components/DropdownSimpleExample.vue')['default']
    Input: typeof import('./.vitepress/components/theme-editor/Input.vue')['default']
    LayoutBlank: typeof import('./.vitepress/components/LayoutBlank.vue')['default']
    MenuSimpleExample: typeof import('./.vitepress/components/MenuSimpleExample.vue')['default']
    Modal: typeof import('./.vitepress/components/theme-editor/Modal.vue')['default']
    OffsetExample: typeof import('./.vitepress/components/OffsetExample.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sandbox: typeof import('./.vitepress/components/theme-editor/Sandbox.vue')['default']
    SponsorButton: typeof import('./.vitepress/components/SponsorButton.vue')['default']
    StyleEditor: typeof import('./.vitepress/components/theme-editor/StyleEditor.vue')['default']
    SubMenuExample: typeof import('./.vitepress/components/SubMenuExample.vue')['default']
    Tabs: typeof import('./.vitepress/components/theme-editor/Tabs.vue')['default']
    ThemeEditor: typeof import('./.vitepress/components/ThemeEditor.vue')['default']
    ThemesExplorer: typeof import('./.vitepress/components/theme-editor/ThemesExplorer.vue')['default']
    TooltipAsync: typeof import('./.vitepress/components/TooltipAsync.vue')['default']
    TooltipComponentExample: typeof import('./.vitepress/components/TooltipComponentExample.vue')['default']
    TooltipHtml: typeof import('./.vitepress/components/TooltipHtml.vue')['default']
    TooltipPlacement: typeof import('./.vitepress/components/TooltipPlacement.vue')['default']
    TooltipSimpleExample: typeof import('./.vitepress/components/TooltipSimpleExample.vue')['default']
    ZoomShowOnlyExample: typeof import('./.vitepress/components/ZoomShowOnlyExample.vue')['default']
  }
}
